#server:
#  servlet:
#    context-path: /security-springboot
spring:
  application:
    name: security-springboot
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/user_db?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver